version: '3.9'
services:
  nodejs:
    build:
      context: .
      target: local
    image: p2p-service:local
    container_name: p2p-node
    restart: unless-stopped
    tty: true
    environment:
      - PORT=8080
      - MONGODB_URL=mongodb+srv://p2p:p2p@cluster0.d7yqw1g.mongodb.net/?retryWrites=true&w=majority
      - DB_NAME=p2p
    volumes:
      - ./:/usr/src/app
    ports:
      - 9229:9229
      - 8020:8080
